name: This is the Game
on:
  push:
    branches:
      - github-actions

jobs:
  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main


  linters:
    name: Run Python linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencis
        run: pip install black pylint

      - name: Run the linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true
