name: CI Pipeline on PR

on:
  pull_request:
    types: 
      - opened
      - reopened
    branches:
      - main
      
    paths:
      - '**.py'
      - Dockerfile

jobs:
  run-linters:
    name: Run Python linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black flake8

      - name: Run the linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          pylint: true

      - name: Run Dockerfile linter
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
